### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by polikin** [guardian/guss-rem#1]
When I imported your .scss, I have this error:

 Invalid CSS after "...@each $property": expected "in", was ", $value in $pr...")
overwrite css/main.css 

*Compile with Prepros.

**Comment by kaelig** [comment]
Sorry, looks like you're running Sass 3.2 and it was said nowhere that Sass 3.3 was a requirement (I just documented it in the readme).

Any chance you can set Prepros to use Sass 3.3?

**Comment by polikin** [comment]
I use my local version of sass, so I will update it to 3.3.

Thanks!
