### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by paintedbicycle** [guardian/guss-rem#11]
Hey,

I'm still using guss-rem but I've been trying to reduce the amount of dependency management I have to do. I find myself only using Bower to use this plugin, as almost everything else has either been moved to npm or also registered themselves on npm. Would you be willing to add guss-rem to npm?

Paul

**Comment by sndrs** [comment]
hi @paintedbicycle 

we've actually stopped using these repos in favour of commiting all the code directly in the guardian frontend repo, so they're unlikely to see updates. in fact, the things we've embedded are close to becoming obsolete internally too.

for these reasons, i think we'd be unlikely to start publishing this on npm, but you could always [install from this repo directly with npm](https://docs.npmjs.com/cli/install#description) – would that help?

**Comment by paintedbicycle** [comment]
Ok thanks!

**Comment by kaelig** [comment]
As the author of this mixin, I’d recommend against using it. Favor a PostCSS plugin instead, such as https://github.com/cuth/postcss-pxtorem
