### ISSUE TITLE
Syntax error: Duplicate key

### ISSUE THREAD

**Issue by paintedbicycle** [guardian/guss-rem#2]
If I wanted to include a fallback inside the rem function, I can get a syntax error of Duplicate key if I do something like this:

```
@include rem((
    padding-top: 20px,
    border-bottom: 10px solid rgb(255,255,255),
    border-bottom: 10px solid rgba(255,255,255,0.05),
));
```

The use case here is small - I can just fallback outside the rem function since the browser that doesn't understand rgba also doesn't understand rem units. Just wanted to flag it in case it revealed a larger bug.

**Comment by kaelig** [comment]
Thanks, unfortunately there is no way around it as keys in Sass maps are unique.
