### ISSUE TITLE
Naming conflict with Bourbon 3.2

### ISSUE THREAD

**Issue by paintedbicycle** [guardian/guss-rem#4]
Not sure if it is because of updating to Sass 3.3.3 or perhaps the grunt task, but all of a sudden I get this error:

```
Running "sass:dev" (sass) task
Syntax error: Mixin rem is missing argument $size
```
- If I comment out that rule, it just gives me the same error on the next rule using rem
- I use $guss-rem-baseline in my stylesheet (have since before this error) so I tried removing it, but it makes no difference to the error

**Comment by kaelig** [comment]
Thanks for reporting it, but according to the unit tests and a Sassmeister test with Sass 3.3.3, the mixin seems to work: http://sassmeister.com/gist/7451284

Can you investigate further on your side?

**Comment by paintedbicycle** [comment]
Seems to be a conflict with the Bourbon.io 3.2.0 beta-2 release. https://github.com/thoughtbot/bourbon

When I comment out Bourbon the error goes away. Namespacing issue? I can look into it more after work if you like.

**Comment by kaelig** [comment]
Classic naming clash. Unfortunately I have no plans to change the name of the mixin because for something so simple I think it should have a short name.

If you like guss-rem better than Bourbon's `rem()` mixin, you could open a PR on bourbon suggesting them to use guss-rem.

**Comment by kaelig** [comment]
(I took the liberty to change the title of the issue for search & log purposes)
